#!/bin/bash
REGEX="^notAfter=(.*)"

servers=(
practable.io
book.practable.io
relay.practable.io
shell.practable.io
static.practable.io
)

for s in ${servers[@]}; do

  date=$(./check-cert $s | grep notAfter)
  [[ $date =~ $REGEX ]]
  date="${BASH_REMATCH[1]}"
  printf '%-20s' $s
  echo $date

done

