#!/bin/bash
# pipe token into script

# https://gist.github.com/angelo-v/e0208a18d455e2e6ea3c40ad637aac53
# pad base64URL encoded to base64
paddit() {
  input=$1
  l=`echo -n $input | wc -c`
  while [ `expr $l % 4` -ne 0 ]
  do
    input="${input}="
    l=`echo -n $input | wc -c`
  done
  echo $input
}
read jwt
## read the first argument and parse into sections
read h p s <<< $(echo $jwt | tr [-_] [+/] | sed 's/\./ /g')

h=`paddit $h`
p=`paddit $p`

# assuming we have jq installed
echo $h | base64 -d | jq
echo $p | base64 -d | jq

exp=$(echo $p | base64 -d | jq '.exp')
expdate=$(date -d "@${exp}")

iat=$(echo $p | base64 -d | jq '.iat')
iatdate=$(date -d "@${iat}")

nbf=$(echo $p | base64 -d | jq '.nbf')
nbfdate=$(date -d "@${nbf}")

echo "exp: ${expdate}"
echo "iat: ${iatdate}"
echo "nbf: ${nbfdate}"
