#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 23 14:50:27 2023

@author: tim
"""

# usage: generate-bookings #uses ./data/booking-plan.yaml
# usage: generate-bookings some-other-booking-plan.yaml

import datetime
import json
import random
import string
import sys
import yaml


symbols = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789" #avoid 0,O, l,1
codes_used = {}

def code(length):
    return ''.join(random.choice(symbols) for i in range(length))

def unique_code():
    c = code(6)
    
    while c in codes_used: #try again until not found in list
        c = code(8)
    
    codes_used[c]=True
    return c
    
    

# https://stackoverflow.com/questions/3844801/check-if-all-elements-in-a-list-are-identical
def all_equal(iterator):
    iterator = iter(iterator)
    try:
        first = next(iterator)
    except StopIteration:
        return True
    return all(first == x for x in iterator)

# modified from https://yaml-core.narkive.com/20GMqy7V/how-to-force-pyyaml-to-dump-date-with-a-z-at-the-end
yaml.add_representer(datetime.datetime, lambda self, data:
                     self.represent_scalar('tag:yaml.org,2002:str', data.replace(tzinfo=None).isoformat('T') +'Z'))   

booking_plan = "./data/booking-plan.yaml"

if (len(sys.argv) > 1):
    booking_plan = sys.argv[1]

f = open(booking_plan, "r")

document = f.read()

obj = yaml.safe_load(document)
#print(obj)
#print(obj.keys())

#print(obj["sessions"])

# check slot lists are the same length
slot_lists =  obj["slot_lists"]

lengths = []

for item in slot_lists:
    lengths.append(len(slot_lists[item]["slots"]))

if not all_equal(lengths):
    print("slot lists lengths do not match")
    for item in slot_lists:
        print(item + ": " + str(len(slot_lists[item]["slots"])))
    exit(1)

slot_count = lengths[0]    

generated_bookings = []    
session_links=[]
session_stub="https://dev.practable.io/book/?s="
descriptions=[]
for name in obj["sessions"]:
 
    session = obj["sessions"][name]
    
    earliest = session["bookings"][0]["start"]
    latest = session["bookings"][0]["end"]
    
    bookings = session["bookings"]
    
    for booking in bookings:
        if booking["start"] < earliest:
            earliest = booking["start"]
        if booking["end"] > latest:
            latest = booking["end"]           
    
    begins=earliest.strftime("%Y-%b-%d-%a-%H%M")
    ends = latest.strftime("%H%M")
    
    for i in range(slot_count):
        c = unique_code()
        description = '-'.join([session["prefix"], begins,ends,session["suffix"], format(i, '03d'),c])
        
        session_links.append(session_stub + c + "\n")
        descriptions.append(description)
     
        bi = 0
        for booking in bookings:
 
            slot = slot_lists[booking["slot_list"]]["slots"][i]
            policy = slot_lists[booking["slot_list"]]["policy"]
           
            generated_bookings.append({
                    "name": c + "-" + format(bi, '02d'),
                    "user": c,
                    "slot": slot,
                    "policy": policy,
                    "when": {
                            "start": booking["start"].replace(tzinfo=None).isoformat('T') +'Z',
                            "end": booking["end"].replace(tzinfo=None).isoformat('T') +'Z'
                        }
                })
            bi=bi+1
            
            
#print(generated_bookings)         
   

#print(yaml.dump(generated_bookings, default_flow_style=False))
with open(r'./data/generated_bookings.yaml', 'w') as file:
    yaml.dump(generated_bookings, file, default_flow_style=False)
    
with open(r'./data/generated_bookings.json', 'w') as file:
    json.dump(generated_bookings, file) 
    

lines = []

for description, link in zip(descriptions, session_links):
    lines.append(description + ", " + link + "\n")
    
    
with open(r'./data/booking-links.txt', 'w') as file:
        file.writelines(lines)

