#!/bin/bash

#example ./set-slot sl-engdes1-spin46 false "offline%20today"

export BOOK_CLIENT_HOST=dev.practable.io
export BOOK_CLIENT_BASE_PATH=/book/api/v1
export BOOK_CLIENT_SCHEME=https
export BOOK_CLIENT_SECRET=$(cat ~/secret/v0/book.pat)
export BOOK_CLIENT_TOKEN_AUD=https://dev.practable.io/book
export BOOK_CLIENT_TOKEN_TTL=5m
export BOOK_CLIENT_TOKEN_ADMIN=true
export BOOK_CLIENT_TOKEN_SUB=admin
export BOOK_CLIENT_TOKEN=$(../bin/book token)

curl -X 'PUT' \
  "https://dev.practable.io/book/api/v1/admin/slots/$1?available=$2&reason=$3" \
  -H 'accept: application/json' \
  -H "Content-Type: application/json" \
  -H "Authorization: ${BOOK_CLIENT_TOKEN}"

./get-slot $1
