#!/bin/sh
dataAccess=$(cat /etc/practable/data.access)
dataToken=$(cat /etc/practable/data.token)
videoAccess=$(cat /etc/practable/video.access)
videoToken=$(cat /etc/practable/video.token)

curl -X POST -H "Content-Type: application/json" -d '{"stream":"video","destination":"'"${videoAccess}"'","id":"0","token":"'"${videoToken}"'"}' http://localhost:8888/api/destinations
curl -X POST -H "Content-Type: application/json" -d '{"stream":"data","destination":"'"${dataAccess}"'","id":"1","token":"'"${dataToken}"'"}' http://localhost:8888/api/destinations 


dataAccess=$(cat /etc/practable/st-data.access)
dataToken=$(cat /etc/practable/st-data.token)
videoAccess=$(cat /etc/practable/st-video.access)
videoToken=$(cat /etc/practable/st-video.token)

curl -X POST -H "Content-Type: application/json" -d '{"stream":"video","destination":"'"${videoAccess}"'","id":"2","token":"'"${videoToken}"'"}' http://localhost:8888/api/destinations
curl -X POST -H "Content-Type: application/json" -d '{"stream":"data","destination":"'"${dataAccess}"'","id":"3","token":"'"${dataToken}"'"}' http://localhost:8888/api/destinations
